### PR TITLE
Added ShrutiJagwani to CONTRIBUTORS.md and participant.html

### LINKED ISSUE #1: Add your name to the CONTRIBUTORS.md file

### PR DESCRIPTION
**Pull request by shruti8019**
fixes #1 and #2

### CODE REVIEW

**Comment by dbads** [comment]
You need to request for verification on https://contrihubs.herokuapp.com/l for achieving points for your pr.

Good first PR though :+1:  :smile:

**Comment by dbads** [comment]
Now you can also add yourself to participants.html :smile:

**Comment by dbads** [comment]
Create a request on https://contrihubs.herokuapp.com/ for getting points for this pr.
Solve more weighted issues to achieve points and get on leaderboard. smile

**Comment by shruti8019** [comment]
I have already added myself to participants.html in the previous PR. Do i
need to add myself again?

**Pull request closed without merging**
