### PR TITLE
Added AbhishekKumar to participant.html and CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by abhi1358**

### CODE REVIEW

**Comment by abhi1358** [comment]
fixes #1 and #2.

**Comment by dbads** [comment]
Cool :+1:

**Comment by dbads** [comment]
Good first pr :+1: 
keep hunting more issues :smile:

**Comment by dbads** [comment]
Create a request on https://contrihubs.herokuapp.com/ for getting points for this pr.
Solve more weighted issues to achieve points and get on leaderboard. :smile:

**Comment by dbads** [comment]
You haven't added your pic in img/profile folder. Do it to see it on participants.html page.

**Pull request merged**
